# See https://fly.io/docs/reference/configuration/ for information about how to use this file.

app = "pokedoku"
primary_region = "iad"

[build]

[env]
  NODE_ENV = "production"
  # SQLite DB stored on persistent volume
  DATABASE_PATH = "/data/pokedoku.db"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0

[mounts]
  source = "pokedoku_data"
  destination = "/data"

[[vm]]
  size = "shared-cpu-1x"
  memory = "512mb"
