// Pokémon data for grid categories and answer validation
// Loads from pokemon-data.json (generated by `npm run fetch-pokemon`) if available,
// otherwise falls back to a curated built-in set.

import type { CategoryType, Category, Pokemon } from "./types";

export type { CategoryType, Category, Pokemon };

// Try to load the full PokéAPI-sourced dataset
let pokemonData: Pokemon[];
try {
  // eslint-disable-next-line @typescript-eslint/no-require-imports
  pokemonData = require("./pokemon-data.json") as Pokemon[];
  console.log(`Loaded ${pokemonData.length} Pokémon from PokéAPI dataset`);
} catch {
  // Fall back to curated built-in data
  pokemonData = require("./pokemon-fallback").FALLBACK_POKEMON as Pokemon[];
  console.log(`Using fallback dataset (${pokemonData.length} Pokémon). Run "npm run fetch-pokemon" for the full set.`);
}

export const POKEMON: Pokemon[] = pokemonData;

// Categories that can be used as row/column headers
export const CATEGORIES: Category[] = [
  // Types
  { id: "type-normal", label: "Normal Type", type: "type" },
  { id: "type-fire", label: "Fire Type", type: "type" },
  { id: "type-water", label: "Water Type", type: "type" },
  { id: "type-electric", label: "Electric Type", type: "type" },
  { id: "type-grass", label: "Grass Type", type: "type" },
  { id: "type-ice", label: "Ice Type", type: "type" },
  { id: "type-fighting", label: "Fighting Type", type: "type" },
  { id: "type-poison", label: "Poison Type", type: "type" },
  { id: "type-ground", label: "Ground Type", type: "type" },
  { id: "type-flying", label: "Flying Type", type: "type" },
  { id: "type-psychic", label: "Psychic Type", type: "type" },
  { id: "type-bug", label: "Bug Type", type: "type" },
  { id: "type-rock", label: "Rock Type", type: "type" },
  { id: "type-ghost", label: "Ghost Type", type: "type" },
  { id: "type-dragon", label: "Dragon Type", type: "type" },
  { id: "type-dark", label: "Dark Type", type: "type" },
  { id: "type-steel", label: "Steel Type", type: "type" },
  { id: "type-fairy", label: "Fairy Type", type: "type" },

  // Generations
  { id: "gen-1", label: "Gen 1 (Kanto)", type: "generation" },
  { id: "gen-2", label: "Gen 2 (Johto)", type: "generation" },
  { id: "gen-3", label: "Gen 3 (Hoenn)", type: "generation" },
  { id: "gen-4", label: "Gen 4 (Sinnoh)", type: "generation" },
  { id: "gen-5", label: "Gen 5 (Unova)", type: "generation" },
  { id: "gen-6", label: "Gen 6 (Kalos)", type: "generation" },
  { id: "gen-7", label: "Gen 7 (Alola)", type: "generation" },
  { id: "gen-8", label: "Gen 8 (Galar)", type: "generation" },
  { id: "gen-9", label: "Gen 9 (Paldea)", type: "generation" },

  // Egg Groups
  { id: "egg-monster", label: "Monster Egg Group", type: "egg_group" },
  { id: "egg-water1", label: "Water 1 Egg Group", type: "egg_group" },
  { id: "egg-water2", label: "Water 2 Egg Group", type: "egg_group" },
  { id: "egg-water3", label: "Water 3 Egg Group", type: "egg_group" },
  { id: "egg-bug", label: "Bug Egg Group", type: "egg_group" },
  { id: "egg-flying", label: "Flying Egg Group", type: "egg_group" },
  { id: "egg-field", label: "Field Egg Group", type: "egg_group" },
  { id: "egg-fairy", label: "Fairy Egg Group", type: "egg_group" },
  { id: "egg-grass", label: "Grass Egg Group", type: "egg_group" },
  { id: "egg-humanlike", label: "Human-Like Egg Group", type: "egg_group" },
  { id: "egg-mineral", label: "Mineral Egg Group", type: "egg_group" },
  { id: "egg-amorphous", label: "Amorphous Egg Group", type: "egg_group" },
  { id: "egg-ditto", label: "Ditto Egg Group", type: "egg_group" },
  { id: "egg-dragon", label: "Dragon Egg Group", type: "egg_group" },
  { id: "egg-undiscovered", label: "Undiscovered Egg Group", type: "egg_group" },

  // Evolution
  { id: "evo-none", label: "Doesn't Evolve", type: "evolution" },
  { id: "evo-stone", label: "Evolves by Stone", type: "evolution" },
  { id: "evo-trade", label: "Evolves by Trade", type: "evolution" },
  { id: "evo-friendship", label: "Evolves by Friendship", type: "evolution" },
  { id: "evo-level", label: "Evolves by Level Up", type: "evolution" },
  { id: "evo-has-mega", label: "Has Mega Evolution", type: "evolution" },

  // Status
  { id: "status-legendary", label: "Legendary", type: "status" },
  { id: "status-mythical", label: "Mythical", type: "status" },
  { id: "status-pseudo", label: "Pseudo-Legendary", type: "status" },
  { id: "status-starter", label: "Starter Pokémon", type: "status" },
  { id: "status-fossil", label: "Fossil Pokémon", type: "status" },
  { id: "status-baby", label: "Baby Pokémon", type: "status" },
  { id: "status-ultra-beast", label: "Ultra Beast", type: "status" },
  { id: "status-paradox", label: "Paradox Pokémon", type: "status" },
];

// Map from egg group category ID suffix to the egg group names used in PokéAPI data
const EGG_GROUP_MAP: Record<string, string[]> = {
  monster: ["monster"],
  water1: ["water1"],
  water2: ["water2"],
  water3: ["water3"],
  bug: ["bug"],
  flying: ["flying"],
  field: ["field"],
  fairy: ["fairy"],
  grass: ["grass", "plant"],
  humanlike: ["humanlike", "human-like", "humanshape"],
  mineral: ["mineral"],
  amorphous: ["amorphous", "indeterminate"],
  ditto: ["ditto"],
  dragon: ["dragon"],
  undiscovered: ["undiscovered", "no-eggs"],
};

// Check if a Pokémon matches a given category
export function pokemonMatchesCategory(pokemon: Pokemon, categoryId: string): boolean {
  const dashIdx = categoryId.indexOf("-");
  const group = categoryId.substring(0, dashIdx);
  const value = categoryId.substring(dashIdx + 1);

  switch (group) {
    case "type":
      return pokemon.types.includes(value);
    case "gen":
      return pokemon.generation === parseInt(value);
    case "egg": {
      const validNames = EGG_GROUP_MAP[value] || [value];
      return pokemon.eggGroups.some(eg =>
        validNames.some(valid => eg.toLowerCase().replace(/[- ]/g, "") === valid.toLowerCase().replace(/[- ]/g, ""))
      );
    }
    case "evo":
      return pokemon.evolutionMethod.includes(value);
    case "status":
      return pokemon.status.includes(value);
    default:
      return false;
  }
}

// Find a Pokémon by name (case-insensitive)
export function findPokemon(name: string): Pokemon | undefined {
  return POKEMON.find(p => p.name.toLowerCase() === name.toLowerCase());
}

// Get all Pokémon matching a category
export function getPokemonForCategory(categoryId: string): Pokemon[] {
  return POKEMON.filter(p => pokemonMatchesCategory(p, categoryId));
}

// Check if any Pokémon can satisfy both categories (for grid validation)
export function hasValidAnswer(rowCategoryId: string, colCategoryId: string): boolean {
  return POKEMON.some(p =>
    pokemonMatchesCategory(p, rowCategoryId) && pokemonMatchesCategory(p, colCategoryId)
  );
}

// Get all Pokémon names for autocomplete
export function getAllPokemonNames(): string[] {
  return POKEMON.map(p => p.name).sort();
}

// Get Pokémon names filtered by both row and column category (for Create/Edit grid cells)
export function getFilteredPokemonNames(rowCategoryId?: string, colCategoryId?: string, exclude?: Set<string>): string[] {
  let filtered = POKEMON;
  if (rowCategoryId) {
    filtered = filtered.filter(p => pokemonMatchesCategory(p, rowCategoryId));
  }
  if (colCategoryId) {
    filtered = filtered.filter(p => pokemonMatchesCategory(p, colCategoryId));
  }
  let names = filtered.map(p => p.name).sort();
  if (exclude && exclude.size > 0) {
    names = names.filter(n => !exclude.has(n));
  }
  return names;
}

// Get sprite URL for a Pokémon (uses PokéAPI sprites)
export function getPokemonSpriteUrl(name: string): string | null {
  const pokemon = findPokemon(name);
  if (!pokemon) return null;
  return `https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/${pokemon.dexNumber}.png`;
}
