// Pokémon data for grid categories and answer validation
// Loads from pokemon-data.json (generated by `npm run fetch-pokemon`) if available,
// otherwise falls back to a curated built-in set.

import type { CategoryType, Category, Pokemon } from "./types";

export type { CategoryType, Category, Pokemon };

// Try to load the full PokéAPI-sourced dataset
let pokemonData: Pokemon[];
try {
  // eslint-disable-next-line @typescript-eslint/no-require-imports
  pokemonData = require("./pokemon-data.json") as Pokemon[];
  console.log(`Loaded ${pokemonData.length} Pokémon from PokéAPI dataset`);
} catch {
  // Fall back to curated built-in data
  pokemonData = require("./pokemon-fallback").FALLBACK_POKEMON as Pokemon[];
  console.log(`Using fallback dataset (${pokemonData.length} Pokémon). Run "npm run fetch-pokemon" for the full set.`);
}

export const POKEMON: Pokemon[] = pokemonData;

// Categories that can be used as row/column headers
export const CATEGORIES: Category[] = [
  // Types
  { id: "type-normal", label: "Normal Type", type: "type" },
  { id: "type-fire", label: "Fire Type", type: "type" },
  { id: "type-water", label: "Water Type", type: "type" },
  { id: "type-electric", label: "Electric Type", type: "type" },
  { id: "type-grass", label: "Grass Type", type: "type" },
  { id: "type-ice", label: "Ice Type", type: "type" },
  { id: "type-fighting", label: "Fighting Type", type: "type" },
  { id: "type-poison", label: "Poison Type", type: "type" },
  { id: "type-ground", label: "Ground Type", type: "type" },
  { id: "type-flying", label: "Flying Type", type: "type" },
  { id: "type-psychic", label: "Psychic Type", type: "type" },
  { id: "type-bug", label: "Bug Type", type: "type" },
  { id: "type-rock", label: "Rock Type", type: "type" },
  { id: "type-ghost", label: "Ghost Type", type: "type" },
  { id: "type-dragon", label: "Dragon Type", type: "type" },
  { id: "type-dark", label: "Dark Type", type: "type" },
  { id: "type-steel", label: "Steel Type", type: "type" },
  { id: "type-fairy", label: "Fairy Type", type: "type" },

  // Generations
  { id: "gen-1", label: "Gen 1 (Kanto)", type: "generation" },
  { id: "gen-2", label: "Gen 2 (Johto)", type: "generation" },
  { id: "gen-3", label: "Gen 3 (Hoenn)", type: "generation" },
  { id: "gen-4", label: "Gen 4 (Sinnoh)", type: "generation" },
  { id: "gen-5", label: "Gen 5 (Unova)", type: "generation" },
  { id: "gen-6", label: "Gen 6 (Kalos)", type: "generation" },
  { id: "gen-7", label: "Gen 7 (Alola)", type: "generation" },
  { id: "gen-8", label: "Gen 8 (Galar)", type: "generation" },
  { id: "gen-9", label: "Gen 9 (Paldea)", type: "generation" },

  // Evolution
  { id: "evo-none", label: "Doesn't Evolve", type: "evolution" },
  { id: "evo-stone", label: "Evolves by Stone", type: "evolution" },
  { id: "evo-trade", label: "Evolves by Trade", type: "evolution" },
  { id: "evo-friendship", label: "Evolves by Friendship", type: "evolution" },
  { id: "evo-level", label: "Evolves by Level Up", type: "evolution" },
  { id: "evo-has-mega", label: "Has Mega Evolution", type: "evolution" },

  // Status
  { id: "status-legendary", label: "Legendary", type: "status" },
  { id: "status-mythical", label: "Mythical", type: "status" },
  { id: "status-pseudo", label: "Pseudo-Legendary", type: "status" },
  { id: "status-starter", label: "Starter Pokémon", type: "status" },
  { id: "status-fossil", label: "Fossil Pokémon", type: "status" },
  { id: "status-baby", label: "Baby Pokémon", type: "status" },
  { id: "status-ultra-beast", label: "Ultra Beast", type: "status" },
  { id: "status-paradox", label: "Paradox Pokémon", type: "status" },

  // Weakness (takes super-effective damage from this type)
  { id: "weak-fire", label: "Weak to Fire", type: "weakness" },
  { id: "weak-water", label: "Weak to Water", type: "weakness" },
  { id: "weak-electric", label: "Weak to Electric", type: "weakness" },
  { id: "weak-grass", label: "Weak to Grass", type: "weakness" },
  { id: "weak-ice", label: "Weak to Ice", type: "weakness" },
  { id: "weak-fighting", label: "Weak to Fighting", type: "weakness" },
  { id: "weak-poison", label: "Weak to Poison", type: "weakness" },
  { id: "weak-ground", label: "Weak to Ground", type: "weakness" },
  { id: "weak-flying", label: "Weak to Flying", type: "weakness" },
  { id: "weak-psychic", label: "Weak to Psychic", type: "weakness" },
  { id: "weak-bug", label: "Weak to Bug", type: "weakness" },
  { id: "weak-rock", label: "Weak to Rock", type: "weakness" },
  { id: "weak-ghost", label: "Weak to Ghost", type: "weakness" },
  { id: "weak-dragon", label: "Weak to Dragon", type: "weakness" },
  { id: "weak-dark", label: "Weak to Dark", type: "weakness" },
  { id: "weak-steel", label: "Weak to Steel", type: "weakness" },
  { id: "weak-fairy", label: "Weak to Fairy", type: "weakness" },
  { id: "weak-normal", label: "Weak to Normal", type: "weakness" },

  // Resistance (takes not-very-effective or no damage from this type)
  { id: "resists-fire", label: "Resists Fire", type: "resistance" },
  { id: "resists-water", label: "Resists Water", type: "resistance" },
  { id: "resists-electric", label: "Resists Electric", type: "resistance" },
  { id: "resists-grass", label: "Resists Grass", type: "resistance" },
  { id: "resists-ice", label: "Resists Ice", type: "resistance" },
  { id: "resists-fighting", label: "Resists Fighting", type: "resistance" },
  { id: "resists-poison", label: "Resists Poison", type: "resistance" },
  { id: "resists-ground", label: "Resists Ground", type: "resistance" },
  { id: "resists-flying", label: "Resists Flying", type: "resistance" },
  { id: "resists-psychic", label: "Resists Psychic", type: "resistance" },
  { id: "resists-bug", label: "Resists Bug", type: "resistance" },
  { id: "resists-rock", label: "Resists Rock", type: "resistance" },
  { id: "resists-ghost", label: "Resists Ghost", type: "resistance" },
  { id: "resists-dragon", label: "Resists Dragon", type: "resistance" },
  { id: "resists-dark", label: "Resists Dark", type: "resistance" },
  { id: "resists-steel", label: "Resists Steel", type: "resistance" },
  { id: "resists-fairy", label: "Resists Fairy", type: "resistance" },
  { id: "resists-normal", label: "Resists Normal", type: "resistance" },

  // Weight and Height categories are dynamic (pokemon-relative) — see getLabelForCategoryId / pokemonMatchesCategory
];

// --- New categories: weakness, resistance, weight, height ---

const POKEMON_TYPES = [
  "normal", "fire", "water", "electric", "grass", "ice",
  "fighting", "poison", "ground", "flying", "psychic", "bug",
  "rock", "ghost", "dragon", "dark", "steel", "fairy",
];

// Type effectiveness chart: TYPE_EFFECTIVENESS[attackType][defendType] = multiplier
// Missing entries default to 1x (neutral)
const TYPE_EFFECTIVENESS: Record<string, Record<string, number>> = {
  normal:   { rock: 0.5, ghost: 0, steel: 0.5 },
  fire:     { fire: 0.5, water: 0.5, grass: 2, ice: 2, bug: 2, rock: 0.5, dragon: 0.5, steel: 2 },
  water:    { fire: 2, water: 0.5, grass: 0.5, ground: 2, rock: 2, dragon: 0.5 },
  electric: { water: 2, electric: 0.5, grass: 0.5, ground: 0, flying: 2, dragon: 0.5 },
  grass:    { fire: 0.5, water: 2, grass: 0.5, poison: 0.5, ground: 2, flying: 0.5, bug: 0.5, rock: 2, dragon: 0.5, steel: 0.5 },
  ice:      { water: 0.5, grass: 2, ice: 0.5, ground: 2, flying: 2, dragon: 2, steel: 0.5 },
  fighting: { normal: 2, ice: 2, poison: 0.5, flying: 0.5, psychic: 0.5, bug: 0.5, rock: 2, ghost: 0, dark: 2, steel: 2, fairy: 0.5 },
  poison:   { grass: 2, poison: 0.5, ground: 0.5, rock: 0.5, ghost: 0.5, steel: 0, fairy: 2 },
  ground:   { fire: 2, electric: 2, grass: 0.5, poison: 2, flying: 0, bug: 0.5, rock: 2, steel: 2 },
  flying:   { electric: 0.5, grass: 2, fighting: 2, bug: 2, rock: 0.5, steel: 0.5 },
  psychic:  { fighting: 2, poison: 2, psychic: 0.5, dark: 0, steel: 0.5 },
  bug:      { fire: 0.5, grass: 2, fighting: 0.5, poison: 0.5, flying: 0.5, psychic: 2, ghost: 0.5, dark: 2, steel: 0.5, fairy: 0.5 },
  rock:     { fire: 2, ice: 2, fighting: 0.5, ground: 0.5, flying: 2, bug: 2, steel: 0.5 },
  ghost:    { normal: 0, psychic: 2, ghost: 2, dark: 0.5 },
  dragon:   { dragon: 2, steel: 0.5, fairy: 0 },
  dark:     { fighting: 0.5, psychic: 2, ghost: 2, dark: 0.5, fairy: 0.5 },
  steel:    { fire: 0.5, water: 0.5, electric: 0.5, ice: 2, rock: 2, steel: 0.5, fairy: 2 },
  fairy:    { fire: 0.5, fighting: 2, poison: 0.5, dragon: 2, dark: 2, steel: 0.5 },
};

function calcTypeEffectiveness(attackType: string, defTypes: string[]): number {
  const chart = TYPE_EFFECTIVENESS[attackType] || {};
  let mult = 1;
  for (const dt of defTypes) mult *= chart[dt] ?? 1;
  return mult;
}

// Map from egg group category ID suffix to the egg group names used in PokéAPI data
const EGG_GROUP_MAP: Record<string, string[]> = {
  monster: ["monster"],
  water1: ["water1"],
  water2: ["water2"],
  water3: ["water3"],
  bug: ["bug"],
  flying: ["flying"],
  field: ["field"],
  fairy: ["fairy"],
  grass: ["grass", "plant"],
  humanlike: ["humanlike", "human-like", "humanshape"],
  mineral: ["mineral"],
  amorphous: ["amorphous", "indeterminate"],
  ditto: ["ditto"],
  dragon: ["dragon"],
  undiscovered: ["undiscovered", "no-eggs"],
};

// Check if a Pokémon matches a given category
export function pokemonMatchesCategory(pokemon: Pokemon, categoryId: string): boolean {
  const dashIdx = categoryId.indexOf("-");
  if (dashIdx === -1) return false;
  const group = categoryId.substring(0, dashIdx);
  const value = categoryId.substring(dashIdx + 1);

  switch (group) {
    case "type":
      return pokemon.types.includes(value);
    case "gen":
      return pokemon.generation === parseInt(value);
    case "egg": {
      const validNames = EGG_GROUP_MAP[value] || [value];
      return pokemon.eggGroups.some(eg =>
        validNames.some(valid => eg.toLowerCase().replace(/[- ]/g, "") === valid.toLowerCase().replace(/[- ]/g, ""))
      );
    }
    case "evo":
      return pokemon.evolutionMethod.includes(value);
    case "status":
      return pokemon.status.includes(value);
    case "weak":
      return calcTypeEffectiveness(value, pokemon.types) > 1;
    case "resists":
      return calcTypeEffectiveness(value, pokemon.types) < 1;
    case "weight": {
      if (pokemon.weight === undefined) return false;
      // value is like "gt-snorlax" or "lt-rattata"
      const sepIdx = value.indexOf("-");
      if (sepIdx === -1) return false;
      const dir = value.substring(0, sepIdx);
      const refName = value.substring(sepIdx + 1);
      const ref = POKEMON.find(p => p.name.toLowerCase() === refName.toLowerCase());
      if (!ref || ref.weight === undefined) return false;
      if (dir === "gt") return pokemon.weight > ref.weight;
      if (dir === "lt") return pokemon.weight < ref.weight;
      return false;
    }
    case "height": {
      if (pokemon.height === undefined) return false;
      // value is like "gt-wailord" or "lt-joltik"
      const sepIdx = value.indexOf("-");
      if (sepIdx === -1) return false;
      const dir = value.substring(0, sepIdx);
      const refName = value.substring(sepIdx + 1);
      const ref = POKEMON.find(p => p.name.toLowerCase() === refName.toLowerCase());
      if (!ref || ref.height === undefined) return false;
      if (dir === "gt") return pokemon.height > ref.height;
      if (dir === "lt") return pokemon.height < ref.height;
      return false;
    }
    case "move":
      return (pokemon.moves || []).includes(value);
    case "ability":
      return (pokemon.abilities || []).includes(value);
    default:
      return false;
  }
}

// Get label for any category ID, including dynamic move/ability categories
export function getLabelForCategoryId(id: string): string {
  const found = CATEGORIES.find(c => c.id === id);
  if (found) return found.label;
  const dashIdx = id.indexOf("-");
  if (dashIdx === -1) return id;
  const group = id.substring(0, dashIdx);
  const value = id.substring(dashIdx + 1);
  if (group === "weight" || group === "height") {
    const sepIdx = value.indexOf("-");
    if (sepIdx !== -1) {
      const dir = value.substring(0, sepIdx);
      const refName = value.substring(sepIdx + 1);
      const displayName = refName.split("-").map(w => w.charAt(0).toUpperCase() + w.slice(1)).join(" ");
      if (group === "weight") {
        if (dir === "gt") return `Heavier than ${displayName}`;
        if (dir === "lt") return `Lighter than ${displayName}`;
      } else {
        if (dir === "gt") return `Taller than ${displayName}`;
        if (dir === "lt") return `Shorter than ${displayName}`;
      }
    }
  }
  const formatted = value.split("-").map(w => w.charAt(0).toUpperCase() + w.slice(1)).join(" ");
  if (group === "move") return `Can learn ${formatted}`;
  if (group === "ability") return `Has ability ${formatted}`;
  return id;
}

// Check if a category ID is valid (static or dynamic move/ability)
export function isValidCategoryId(id: string): boolean {
  if (CATEGORIES.some(c => c.id === id)) return true;
  const dashIdx = id.indexOf("-");
  if (dashIdx === -1) return false;
  const group = id.substring(0, dashIdx);
  const value = id.substring(dashIdx + 1);
  if (group === "move") return getAllMoveNames().includes(value);
  if (group === "ability") return getAllAbilityNames().includes(value);
  if (group === "weight" || group === "height") {
    const sepIdx = value.indexOf("-");
    if (sepIdx === -1) return false;
    const dir = value.substring(0, sepIdx);
    if (dir !== "gt" && dir !== "lt") return false;
    const refName = value.substring(sepIdx + 1);
    return POKEMON.some(p => p.name.toLowerCase() === refName.toLowerCase());
  }
  return false;
}

// Get all unique move slugs across the Pokémon dataset
export function getAllMoveNames(): string[] {
  const moves = new Set<string>();
  for (const p of POKEMON) {
    for (const m of (p.moves || [])) moves.add(m);
  }
  return Array.from(moves).sort();
}

// Get all unique ability slugs across the Pokémon dataset
export function getAllAbilityNames(): string[] {
  const abilities = new Set<string>();
  for (const p of POKEMON) {
    for (const a of (p.abilities || [])) abilities.add(a);
  }
  return Array.from(abilities).sort();
}

// Expose type list for UI
export { POKEMON_TYPES };

// Find a Pokémon by name (case-insensitive)
export function findPokemon(name: string): Pokemon | undefined {
  return POKEMON.find(p => p.name.toLowerCase() === name.toLowerCase());
}

// Get all Pokémon matching a category
export function getPokemonForCategory(categoryId: string): Pokemon[] {
  return POKEMON.filter(p => pokemonMatchesCategory(p, categoryId));
}

// Check if any Pokémon can satisfy both categories (for grid validation)
export function hasValidAnswer(rowCategoryId: string, colCategoryId: string): boolean {
  return POKEMON.some(p =>
    pokemonMatchesCategory(p, rowCategoryId) && pokemonMatchesCategory(p, colCategoryId)
  );
}

// Get all Pokémon names for autocomplete
export function getAllPokemonNames(): string[] {
  return POKEMON.map(p => p.name).sort();
}

// Get Pokémon names filtered by both row and column category (for Create/Edit grid cells)
export function getFilteredPokemonNames(rowCategoryId?: string, colCategoryId?: string, exclude?: Set<string>): string[] {
  let filtered = POKEMON;
  if (rowCategoryId) {
    filtered = filtered.filter(p => pokemonMatchesCategory(p, rowCategoryId));
  }
  if (colCategoryId) {
    filtered = filtered.filter(p => pokemonMatchesCategory(p, colCategoryId));
  }
  let names = filtered.map(p => p.name).sort();
  if (exclude && exclude.size > 0) {
    names = names.filter(n => !exclude.has(n));
  }
  return names;
}

// Get sprite URL for a Pokémon (uses PokéAPI sprites)
export function getPokemonSpriteUrl(name: string): string | null {
  const pokemon = findPokemon(name);
  if (!pokemon) return null;
  return `https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/${pokemon.dexNumber}.png`;
}
